---
openapi: 3.0.0
info:
  title: Web serviсe к сайту Вадима Ксензова
  description: "    Для удобства работы с [сайтом Курс тестирования ПО Вадима Ксендзова](https://ksendzov.com/) планируется добавить три функциональные кнопки:\n`[Запись на курс]`, `[Телеграм для студентов]`, `[Информация о скринингах]`\n\n\nВ данном техническом задании представлен Proxy-сервер, через который происходит перенаправление(отправка) запросов на два WEB-сервиса и возврат запрашиваемых данных, как на сервер назначения. Также endpoints API, методы HTTP запросов и данные request и response для проверки общей работоспособности предложенных для реализации модулей.\n\n\nПроверки для API(описание) были создаданы с помошью [Swagger](https://app.swaggerhub.com/apis/YVASIUKIVICH_1/api/1.0.0#/)\nНекоторые полезные ссылки:\n- [Основная информация](https://github.com/LikhatskayaV/Web_Service/edit/main/README.md)\n\n- [Репозиторий ТЗ для WEB-service](https://github.com/LikhatskayaV/Web_Service)\n\n- [Техническое задание](https://github.com/LikhatskayaV/Web_Service/blob/main/technical_specification.md)\n\n- [Пользовательские требования](https://github.com/LikhatskayaV/Web_Service/blob/main/custom_requirements.md)\n\n- [ссылки на JSON и YAML]() "
  version: 1.0.0
servers:
- url: https://localhost:1425
  description: Proxy server
paths:
  /telegram_group:
    post:
      tags:
      - Telegram group
      summary: Метод получения Списка групп и их описания
      operationId: getAllGroups
      parameters:
      - name: telegram_nick
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Telegram_group'
        "401":
          description: Ошибка в зпросе данные не найдены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'
  /screening_info:
    get:
      tags:
      - Screening info
      summary: Метод получения информации о курсе
      operationId: getAllinfo
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/screening_info'
        default:
          description: Ошибка в зпросе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /Join_course:
    post:
      tags:
      - Join_course
      summary: Метод получения информации о курсе
      operationId: getAllJoin
      parameters:
      - name: telegram_nick
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: Link_Linkidin
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: email
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Join_course'
        default:
          description: Ошибка в зпросе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Telegram_group:
      required:
      - qa_group_curse
      type: object
      properties:
        qa_group_curse:
          type: array
          items:
            type: string
    "401":
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
    screening_info:
      required:
      - Topic1
      - Topic2
      - Topic3
      - Topic4
      - Topic5
      - Topic6
      type: object
      properties:
        Topic1:
          type: string
        Topic2:
          type: string
        Topic3:
          type: string
        Topic4:
          type: string
        Topic5:
          type: string
        Topic6:
          type: string
    Error:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
    Join_course:
      required:
      - Link_Linkidin
      - email
      - telegram_nick
      type: object
      properties:
        telegram_nick:
          type: string
        Link_Linkidin:
          type: string
        email:
          type: string
